### ISSUE TITLE
Adguard DHCP Server

### ISSUE THREAD

**Issue by bayukp** [rm3l/helm-charts#68]
Hi, first of all, thank you very much for amazing charts, really helpful.

I want to ask how I can enable DHCP server correctly, since port 67 / 68 isn't exposed on service and I can't select correct DHCP interface via GUI (Only internal kube interface i can select) 

<img width="1001" alt="image" src="https://github.com/rm3l/helm-charts/assets/25470204/8c56b602-8ffa-47d9-9993-fa762ce67dfb">

**Comment by rm3l** [comment]
Hi @bayukp ,

Thanks!
The container is indeed isolated in its own network namespace, which is why only the internal interface can be seen from within the container.
I think the [`hostNetwork` feature in Kubernetes](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#hosts-namespaces) should allow the container to use the host namespace, and, as such, allow exposing DHCP ports directly on the host.
However, this field cannot be set at the moment in this Chart. I'm currently looking into allowing this, and will share a draft PR that you should be able to try out soon.
The only issue I can think of with `hostNetwork` is in case of conflicts, for example if the container ports started by AdguardHome (like 53 for DNS) are already taken on the host. In this case, I guess you'll need to make sure such ports are not in use on the host.

**Comment by rm3l** [comment]
@bayukp Please take a look at https://github.com/rm3l/helm-charts/pull/76, and please let me know if that helps. Thanks.
